language: c++
os: linux
sudo: false

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - boost-filesystem1.60
      - boost-program-options1.60

addons:
  apt:
    packages:
      - clang-3.6
      - clang-3.7
      - clang-3.8
      - g++-5
      - libgtest-dev
    sources: &sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise

compiler:
  - gcc
  - clang

script:
  - cmake ${CMAKE_OPTIONS} .
  - make
  - ./tests/lib/libnar-tests
