language: cpp
os: linux
sudo: false

addons:
  apt:
    sources: &sources
      - george-edison55-precise-backports # cmake 3.2.3
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise
      - boost-latest
    packages:
      - cmake
      - cmake-data
      - libboost1.55-all-dev
      - clang-3.8
      - g++-5
      - libgtest-dev

compiler:
  - gcc
  - clang

install:
  - mkdir ~/gtest
  - cd ~/gtest
  - export GTEST_LIBRARY_PATH=$(pwd)
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ /usr/src/gtest
  - make
  - cd -
  - export CMAKE_OPTIONS="$CMAKE_OPTIONS -D GTEST_ROOT=${GTEST_LIBRARY_PATH}"
  - if [ ${CXX} == "gcc" ];   then export CMAKE_OPTIONS="${CMAKE_OPTIONS} -D CMAKE_CXX_COMPILER=g++-5";   fi
  - if [ ${CXX} == "clang" ]; then export CMAKE_OPTIONS="${CMAKE_OPTIONS} -D CMAKE_CXX_COMPILER=clang++"; fi

script:
  - cmake ${CMAKE_OPTIONS} .
  - make libnar-tests
  - ./tests/lib/libnar-tests
