language: cpp

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data
      - libgtest-dev
      - libboost-all-dev

compiler:
  - gcc
  - clang

script:
  - cmake .
  - make
  - ./tests/lib/libnar-tests
